### PR TITLE
SPI: Implemented MISO, MOSI, SCK and SS pins handling using avr_bitba…

### PR DESCRIPTION
**Pull request by patrickelectric**
This allows to simulate a 'real' signal time patterns on SPI interface related MCU pins and communicate with diverse devices over it.
Should also fix #222.

Original author: hovercraft-github

### CODE REVIEW

**Comment by patrickelectric** [comment]
@hovercraft-github can you remove the "merge" commit ?

**Comment by patrickelectric** [comment]
It's an empty commit. But I can do that for you.

**Comment by hovercraft-github** [comment]
@patrickelectric My spi_bitbang branch now at dfc7fbe . Is it what you need?

**Comment by patrickelectric** [comment]
@hovercraft-github ty !

**Pull request merged**
